query roles {
  roles {
    role {
      _id
      name
    }
  }
}

query users($currentPage: Int, $perPage: Int, $search: String) {
  users(currentPage: $currentPage, perPage: $perPage, search: $search) {
    total
    users {
      _id
      name {
        first
        last
      }
      emailAddress
      emailVerified
      oAuthProvider
    }
  }
}
