#import "./fragments.gql"

query user($_id: String) {
  user(_id: $_id) {
    ...UserAttributes
  }
}

query userSettings {
  user {
    settings {
      _id
      isGDPR
      key
      label
      type
      value
      lastUpdatedByUser
    }
  }
}

query exportUserData {
  exportUserData {
    zip
  }
}

query oAuthServices($services: [String]) {
  oAuthServices(services: $services)
}

query userSettings {
  userSettings {
    _id
    isGDPR
    key
    label
    type
    value
  }
}
